[2017-11-18 09:07:56] -> ERROR -> [Errno 2] No such file or directory: 'schema.json'
[2017-11-18 09:16:18] -> ERROR -> 'primaryKe'
[2017-11-18 09:16:52] -> ERROR -> 'primaryKe'
[2017-11-18 09:28:19] -> ERROR -> __init__() takes exactly 4 arguments (2 given)
[2017-11-18 09:30:28] -> ERROR -> __init__() takes exactly 4 arguments (2 given)
[2017-11-18 09:47:33] -> ERROR -> 'dict' object has no attribute 'append'
[2017-11-18 10:11:26] -> ERROR -> coercing to Unicode: need string or buffer, int found
[2017-11-18 10:25:15] -> ERROR -> 'users' is not in list
[2017-11-18 10:26:20] -> ERROR -> 'list' object has no attribute 'where'
[2017-11-18 10:28:45] -> ERROR -> list indices must be integers, not tuple
[2017-11-18 10:34:39] -> ERROR -> too many values to unpack
[2017-11-18 10:34:51] -> ERROR -> too many values to unpack
[2017-11-18 10:44:47] -> ERROR -> 'users' is not in list
[2017-11-18 10:45:01] -> ERROR -> 'users' is not in list
[2017-11-18 10:45:20] -> ERROR -> substring not found
[2017-11-18 10:45:30] -> ERROR -> expected a string or other character buffer object
[2017-11-18 10:51:57] -> ERROR -> global name 'get_item_in_pks' is not defined
[2017-11-18 10:52:23] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:54:23] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:54:36] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:55:06] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:55:15] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:55:20] -> ERROR -> list.remove(x): x not in list
[2017-11-18 10:57:50] -> ERROR -> an integer is required
[2017-11-18 10:58:54] -> ERROR -> u'phones' is not in list
[2017-11-18 10:59:05] -> ERROR -> u'id' is not in list
[2017-11-18 10:59:14] -> ERROR -> -2093098020 is not in list
[2017-11-18 11:04:00] -> ERROR -> list.remove(x): x not in list
[2017-11-18 11:05:04] -> ERROR -> list.remove(x): x not in list
[2017-11-18 11:11:47] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 11:13:56] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 11:15:57] -> ERROR -> get_item_in_pks() takes exactly 3 arguments (2 given)
[2017-11-18 11:27:44] -> ERROR -> [Errno 2] No such file or directory: 'schema.json'
[2017-11-18 11:31:59] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 11:51:17] -> ERROR -> append() takes exactly one argument (3 given)
[2017-11-18 12:02:23] -> ERROR -> not all arguments converted during string formatting
[2017-11-18 12:02:32] -> ERROR -> not all arguments converted during string formatting
[2017-11-18 12:03:15] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:03:25] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:03:28] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:03:38] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:03:43] -> ERROR -> 'generator' object has no attribute '__getitem__'
[2017-11-18 12:05:21] -> ERROR -> 'generator' object has no attribute 'item'
[2017-11-18 12:55:02] -> ERROR -> global name 'pks' is not defined
[2017-11-18 12:55:53] -> ERROR -> global name 'pks' is not defined
[2017-11-18 12:58:05] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 12:58:42] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 12:58:57] -> ERROR -> local variable 'pks' referenced before assignment
[2017-11-18 13:10:55] -> ERROR -> local variable 'last_id' referenced before assignment
[2017-11-18 13:15:26] -> ERROR -> local variable 'last_id' referenced before assignment
[2017-11-18 13:15:51] -> ERROR -> local variable 'last_id' referenced before assignment
[2017-11-18 13:16:09] -> ERROR -> 'NoneType' object does not support item assignment
[2017-11-18 13:25:20] -> ERROR -> local variable 'last_id' referenced before assignment
[2017-11-18 13:28:02] -> ERROR -> generate_data() takes no arguments (1 given)
[2017-11-18 13:30:57] -> ERROR -> [Errno 2] No such file or directory: 'one_table_1_1.json'
[2017-11-18 13:39:54] -> ERROR -> No JSON object could be decoded
[2017-11-18 13:40:00] -> ERROR -> Expecting , delimiter: line 15 column 9 (char 285)
[2017-11-18 13:42:39] -> ERROR -> 'reference_table'
[2017-11-19 17:47:49] -> ERROR -> list index out of range
[2017-11-19 17:47:54] -> ERROR -> list index out of range
[2017-11-19 17:47:57] -> ERROR -> list index out of range
[2017-11-19 17:48:07] -> ERROR -> list index out of range
[2017-11-19 17:50:42] -> ERROR -> [Errno 2] No such file or directory: 'two_table_n_n.json'
[2017-11-19 17:51:58] -> ERROR -> tuple index out of range
[2017-11-19 17:52:05] -> ERROR -> tuple indices must be integers, not unicode
[2017-11-19 18:30:23] -> ERROR -> local variable 'g_some_list_aux' referenced before assignment
[2017-11-19 18:42:22] -> ERROR -> 'Namespace' object has no attribute 'V'
[2017-11-19 18:42:34] -> ERROR -> 'Namespace' object has no attribute 'V'
[2017-11-19 18:48:08] -> ERROR -> 'Namespace' object has no attribute 'c'
[2017-11-19 18:54:17] -> ERROR -> 'Namespace' object has no attribute 'c'
[2017-11-19 19:04:54] -> ERROR -> object of type 'bool' has no len()
[2017-11-20 10:24:22] -> ERROR -> [Errno 2] No such file or directory: 'schema.json'
[2017-11-20 11:08:45] -> ERROR -> cannot concatenate 'str' and 'int' objects
[2017-11-20 14:25:05] -> ERROR -> global name 'POSTGRES' is not defined
[2017-11-20 14:25:47] -> ERROR -> [Errno 2] No such file or directory: 'ile_name=oi'
[2017-11-20 14:42:38] -> ERROR -> 'JsonObject' object has no attribute 'tables'
[2017-11-20 14:43:34] -> ERROR -> 'JsonObject' object has no attribute 'tables'
[2017-11-20 14:44:10] -> ERROR -> 'str' object has no attribute 'tables'
[2017-11-20 15:00:42] -> ERROR -> syntax error at or near "CHEC"
LINE 2:     id INTEGER PRIMARY KEY CHEC (id>=0),
                                   ^

[2017-11-20 15:01:36] -> ERROR -> 'psycopg2.extensions.cursor' object has no attribute 'commit'
[2017-11-20 15:31:05] -> ERROR -> cannot concatenate 'str' and 'int' objects
[2017-11-20 15:31:54] -> ERROR -> cannot concatenate 'str' and 'int' objects
[2017-11-20 15:32:31] -> ERROR -> cannot concatenate 'str' and 'int' objects
[2017-11-20 15:32:35] -> ERROR -> global name 'l' is not defined
[2017-11-20 15:35:40] -> ERROR -> cannot concatenate 'str' and 'int' objects
[2017-11-20 15:37:06] -> ERROR -> local variable 'g_bar' referenced before assignment
[2017-11-20 16:33:19] -> ERROR -> global name 'system' is not defined
[2017-11-20 16:41:32] -> ERROR -> global name 'l' is not defined
[2017-11-20 16:45:59] -> ERROR -> local variable 'bar' referenced before assignment
[2017-11-20 16:47:20] -> ERROR -> syntax error at or near "("
LINE 2:     id INTEGER(8) PRIMARY KEY,
                      ^

